# Defi 4,5

In [6]:
import numpy as np

a1 = np.zeros((5, 8, 6))
a1


array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        

In [16]:
a2 = np.arange(4*3*6*8).reshape((4, 3, 6, 8)).ravel()
a2

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [27]:
a3 = np.random.randint(12, size=(5, 8))
a3

array([[ 4, 11,  5,  5,  7,  8,  1,  4],
       [ 1,  8, 11,  8,  4,  8,  6,  3],
       [ 5, 11,  2,  8,  4,  8,  6,  0],
       [10,  8,  2,  2,  0,  8,  2,  2],
       [11,  3,  7,  0,  3,  1,  2,  3]])

In [28]:
a3[a3>5]

array([11,  7,  8,  8, 11,  8,  8,  6, 11,  8,  8,  6, 10,  8,  8, 11,  7])

In [30]:
np.where(a3==10, np.nan, a3) 

array([[ 4., 11.,  5.,  5.,  7.,  8.,  1.,  4.],
       [ 1.,  8., 11.,  8.,  4.,  8.,  6.,  3.],
       [ 5., 11.,  2.,  8.,  4.,  8.,  6.,  0.],
       [nan,  8.,  2.,  2.,  0.,  8.,  2.,  2.],
       [11.,  3.,  7.,  0.,  3.,  1.,  2.,  3.]])

# Pandas


In [2]:
import pandas as pd

df1 = pd.DataFrame({'X':[7,8,9,8,5], 'Y':[4,9,8,3,6],'Z':[6,7,9,2,3]}, index=['row1','row2','row3','row4','row5'])
df1

X  Y  Z
row1  7  4  6
row2  8  9  7
row3  9  8  9
row4  8  3  2
row5  5  6  3

In [3]:
df2 = pd.DataFrame()
df2['X2']=df1['X']**2
df2['Y2']=df1['Y']**3
df2['Z2']=df1['Z']**4
df2

result = pd.concat([df1, df2], axis=1)

result

X  Y  Z  X2   Y2    Z2
row1  7  4  6  49   64  1296
row2  8  9  7  64  729  2401
row3  9  8  9  81  512  6561
row4  8  3  2  64   27    16
row5  5  6  3  25  216    81

In [4]:
df4 = pd.DataFrame( {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, 15, 9, 20, 14.5, 7, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]})
df4

attempts       name  score
0         1  Anastasia   12.5
1         3       Dima    9.0
2         2  Katherine   16.5
3         3      James   15.0
4         2      Emily    9.0
5         3    Michael   20.0
6         1    Matthew   14.5
7         1      Laura    7.0
8         2      Kevin    8.0
9         1      Jonas   19.0

In [21]:
# moy = df4['score'].sum()/df4['attempts'].sum()
moy = (df4["attempts"] * df4["score"]).sum()/df4['attempts'].sum()
print(moy)

res4 = df4[df4['score']>moy]

res4['name']


13.263157894736842


2    Katherine
3        James
5      Michael
6      Matthew
9        Jonas
Name: name, dtype: object